name: baidupan
description: For wrapper baidu netdisk api with dart, user can use the package to query, update ,upload or download for baidu netdisk.
version: 1.2.2
homepage: https://github.com/Caijinglong/baidupan

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  http: ^1.1.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9

executables:
  bd_upload:
  requset_baidu_auth:
